# What the helper may depend on (ADR-0029): crates from crates.io alone, under
# licences compatible with the package's MIT, with no published advisory.

[graph]
all-features = true

[advisories]
yanked = "deny"

[licenses]
allow = ["MIT", "Apache-2.0"]
confidence-threshold = 0.93

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
